<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Payment extends \Zepluf\Bundle\StoreBundle\Entity\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSequenceId($sequenceId)
    {
        $this->__load();
        return parent::setSequenceId($sequenceId);
    }

    public function getSequenceId()
    {
        $this->__load();
        return parent::getSequenceId();
    }

    public function setEffectiveDate($effectiveDate)
    {
        $this->__load();
        return parent::setEffectiveDate($effectiveDate);
    }

    public function getEffectiveDate()
    {
        $this->__load();
        return parent::getEffectiveDate();
    }

    public function setReferenceNumber($referenceNumber)
    {
        $this->__load();
        return parent::setReferenceNumber($referenceNumber);
    }

    public function getReferenceNumber()
    {
        $this->__load();
        return parent::getReferenceNumber();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setPaymentMethodType(\Zepluf\Bundle\StoreBundle\Entity\PaymentMethodType $paymentMethodType = NULL)
    {
        $this->__load();
        return parent::setPaymentMethodType($paymentMethodType);
    }

    public function getPaymentMethodType()
    {
        $this->__load();
        return parent::getPaymentMethodType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'sequenceId', 'effectiveDate', 'referenceNumber', 'amount', 'comment', 'type', 'paymentMethodType');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}