<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PaymentApplication extends \Zepluf\Bundle\StoreBundle\Entity\PaymentApplication implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSequenceId($sequenceId)
    {
        $this->__load();
        return parent::setSequenceId($sequenceId);
    }

    public function getSequenceId()
    {
        $this->__load();
        return parent::getSequenceId();
    }

    public function setAmountApplied($amountApplied)
    {
        $this->__load();
        return parent::setAmountApplied($amountApplied);
    }

    public function getAmountApplied()
    {
        $this->__load();
        return parent::getAmountApplied();
    }

    public function setPayment(\Zepluf\Bundle\StoreBundle\Entity\Payment $payment = NULL)
    {
        $this->__load();
        return parent::setPayment($payment);
    }

    public function getPayment()
    {
        $this->__load();
        return parent::getPayment();
    }

    public function setInvoiceItem(\Zepluf\Bundle\StoreBundle\Entity\InvoiceItem $invoiceItem = NULL)
    {
        $this->__load();
        return parent::setInvoiceItem($invoiceItem);
    }

    public function getInvoiceItem()
    {
        $this->__load();
        return parent::getInvoiceItem();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'sequenceId', 'amountApplied', 'payment', 'invoiceItem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}