<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PartyContactMechanism extends \Zepluf\Bundle\StoreBundle\Entity\PartyContactMechanism implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFromDate($fromDate)
    {
        $this->__load();
        return parent::setFromDate($fromDate);
    }

    public function getFromDate()
    {
        $this->__load();
        return parent::getFromDate();
    }

    public function setThruDate($thruDate)
    {
        $this->__load();
        return parent::setThruDate($thruDate);
    }

    public function getThruDate()
    {
        $this->__load();
        return parent::getThruDate();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setParty(\Zepluf\Bundle\StoreBundle\Entity\Party $party = NULL)
    {
        $this->__load();
        return parent::setParty($party);
    }

    public function getParty()
    {
        $this->__load();
        return parent::getParty();
    }

    public function setContactMechanism(\Zepluf\Bundle\StoreBundle\Entity\ContactMechanism $contactMechanism = NULL)
    {
        $this->__load();
        return parent::setContactMechanism($contactMechanism);
    }

    public function getContactMechanism()
    {
        $this->__load();
        return parent::getContactMechanism();
    }

    public function setPartyRoleType(\Zepluf\Bundle\StoreBundle\Entity\PartyRoleType $partyRoleType = NULL)
    {
        $this->__load();
        return parent::setPartyRoleType($partyRoleType);
    }

    public function getPartyRoleType()
    {
        $this->__load();
        return parent::getPartyRoleType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fromDate', 'thruDate', 'comment', 'party', 'contactMechanism', 'partyRoleType');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}