<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProductFeature extends \Zepluf\Bundle\StoreBundle\Entity\ProductFeature implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setOrder($order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function addProductFeatureValue(\Zepluf\Bundle\StoreBundle\Entity\ProductFeatureValue $productFeatureValue)
    {
        $this->__load();
        return parent::addProductFeatureValue($productFeatureValue);
    }

    public function removeProductFeatureValue(\Zepluf\Bundle\StoreBundle\Entity\ProductFeatureValue $productFeatureValue)
    {
        $this->__load();
        return parent::removeProductFeatureValue($productFeatureValue);
    }

    public function getProductFeatureValue()
    {
        $this->__load();
        return parent::getProductFeatureValue();
    }

    public function addPriceComponent(\Zepluf\Bundle\StoreBundle\Entity\PriceComponent $priceComponent)
    {
        $this->__load();
        return parent::addPriceComponent($priceComponent);
    }

    public function removePriceComponent(\Zepluf\Bundle\StoreBundle\Entity\PriceComponent $priceComponent)
    {
        $this->__load();
        return parent::removePriceComponent($priceComponent);
    }

    public function getPriceComponent()
    {
        $this->__load();
        return parent::getPriceComponent();
    }

    public function setUnitOfMeasurement(\Zepluf\Bundle\StoreBundle\Entity\UnitOfMeasurement $unitOfMeasurement = NULL)
    {
        $this->__load();
        return parent::setUnitOfMeasurement($unitOfMeasurement);
    }

    public function getUnitOfMeasurement()
    {
        $this->__load();
        return parent::getUnitOfMeasurement();
    }

    public function setProductFeatureCategory(\Zepluf\Bundle\StoreBundle\Entity\ProductFeatureCategory $productFeatureCategory = NULL)
    {
        $this->__load();
        return parent::setProductFeatureCategory($productFeatureCategory);
    }

    public function getProductFeatureCategory()
    {
        $this->__load();
        return parent::getProductFeatureCategory();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'description', 'order', 'productFeatureValue', 'priceComponent', 'unitOfMeasurement', 'productFeatureCategory');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}