<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OrderItemRole extends \Zepluf\Bundle\StoreBundle\Entity\OrderItemRole implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setOrderItem(\Zepluf\Bundle\StoreBundle\Entity\OrderItem $orderItem)
    {
        $this->__load();
        return parent::setOrderItem($orderItem);
    }

    public function getOrderItem()
    {
        $this->__load();
        return parent::getOrderItem();
    }

    public function setOrderItemRoleType(\Zepluf\Bundle\StoreBundle\Entity\OrderItemRoleType $orderItemRoleType)
    {
        $this->__load();
        return parent::setOrderItemRoleType($orderItemRoleType);
    }

    public function getOrderItemRoleType()
    {
        $this->__load();
        return parent::getOrderItemRoleType();
    }

    public function setParty(\Zepluf\Bundle\StoreBundle\Entity\Party $party)
    {
        $this->__load();
        return parent::setParty($party);
    }

    public function getParty()
    {
        $this->__load();
        return parent::getParty();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'orderItem', 'orderItemRoleType', 'party');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}