parameters:
  kernel.config_dir: "%kernel.root_dir%/config"

  plugins.root_dir: "%kernel.root_dir%/plugins"

  store.zencart_dir: "%kernel.root_dir%/../vendor/zencart"
  # path to the frontend templates folder
  store.frontend.templates_dir: "%kernel.root_dir%/frontend/templates"
  store.frontend.current_template: "0007"
  # path to the backend templates folder
  store.backend.templates_dir: "%kernel.root_dir%"
  store.backend.current_template: "template_default"
  # absolute path to the website root dir (usually the public_html)
  store.root_dir: "%kernel.root_dir%/../web"
  
  # absolute path to the "web" dir
  web.dir: "%kernel.root_dir%/../web"
  # the relative path from the site root to the "web" folder
  web.relative_dir: ""
  web.cache_dir: "%web.dir%/cache"
  web.images_dir: "%web.dir%/images"

  locale: en
  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     demo
  database_user:     simple_shop
  database_password: simple_shop
  table_prefix:      zen_

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            asd214322dewd1e121eq
