imports:
  - { resource: config.yml }

parameters:
  kernel.debug: true
  web_profiler.debug_toolbar.class: Zepluf\Bundle\StoreBundle\EventListener\WebDebugToolbarListener

framework:
  profiler: { only_exceptions: false }
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: %kernel.debug%

web_profiler:
  toolbar: true
  position: top
  intercept_redirects: false