initalized: true
installed:
    - riPlugin
    - riCore
    - riUtility
    - riCache
    - riSimplex
    - riZCAdmin
    - riCjLoader
    - riResultList
activated:
    - riPlugin
    - riCore
    - riUtility
    - riCache
    - riSimplex
    - riZCAdmin
    - riCjLoader
    - riResultList
backend:
    preload: [riPlugin, riUtility, riCache, riZCAdmin, riCjLoader, riResultList]
frontend:
    preload: [riPlugin, riUtility, riCache, riCjLoader, riResultList]
