# do not ever edit this file

# status
initalized: false

# plugins
installed:

activated:

core:
  - riPlugin
  - riCore
  - riUtility
  - riCache
  - riSimplex
  #- riSession
  - riZCAdmin
  - riCjLoader
  - riResultList

backend:
    preload: []

frontend:
    preload: []