installed:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
    - riBanner
    - riSample
    - riCart
activated:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
    - riCart
    - riBanner
core:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
backend:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
    - riCart
frontend:
    - riPlugin
    - riCache
    - riCjLoader
    - riResultList
    - riCart
    - riBanner
